// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOOTSTRAP_H
#define BOOTSTRAP_H

#include <vector>
#include <iostream>
// #include <fstream> // usando a do boost
#include <cstdio> 
#include <cstdlib> 
#include <string>
#include <time.h>
#include "clusteringTypes.h"

// para incluir as bibliotecas Boost
#include "boost/filesystem/operations.hpp" // includes boost/filesystem/path.hpp
#include "boost/filesystem/fstream.hpp"    // ditto
#include "boost/filesystem/convenience.hpp"    // ditto
#include "boost/lexical_cast.hpp"

namespace fs = boost::filesystem;


//using namespace std;

class bootstrap
{
	public:
		// class constructor
		bootstrap(fs::path fileName, fs::path sampleDir, int nSamples, int sampleSize);
		// class destructor
		//~bootstrap();
};

#endif // BOOTSTRAP_H

